
CREATE PROCEDURE TSP_AGREGARSOLICITUD
(
	@ID_SERV	INT,
	@PIEZA		NVARCHAR(100),
	@DESC		NVARCHAR(200)
)
AS
BEGIN

	IF EXISTS(SELECT SR_ID ID FROM SERVICIO WHERE SR_ID=@ID_SERV)
	BEGIN
		
		INSERT INTO SOLICITUD VALUES(@ID_SERV, 0, @PIEZA, 1, @DESC) 
		SELECT '1' --AGREGADA
	END
	ELSE SELECT '0' -- NO EXIXSTE EL SERVICIO
END
GO

CREATE PROCEDURE TSP_DATOSMAQUINA
(
	@ID_MQ		INT
)
AS
BEGIN

	IF EXISTS(SELECT MQ_ID FROM MAQUINA WHERE @ID_MQ=MQ_ID)
	BEGIN
		SELECT MQ_ID_EMP EMP, MQ_ID_INV INV, MQ_MODELO MODELO, MQ_NOSERIE NOSERIE, MQ_ESTATUS ESTATUS, MQ_PRECIO PRECIO, MQ_DESCRIPCION DESCR, MQ_CONTADOR CONT, MQ_FOTO FOTO, MQ_ULT_SERVICIO ULT  
		FROM MAQUINA
		WHERE MQ_ID = @ID_MQ
	END

END
GO

CREATE PROCEDURE TSP_TERMINARSERVICIO
(
	@ID_SERV INT,
	@SOL NVARCHAR(500),
	@EDO NVARCHAR(500),
	@CONT INT
)
AS
BEGIN
	IF EXISTS(SELECT * FROM SERVICIO WHERE SR_ID=@ID_SERV)
	BEGIN
		UPDATE SERVICIO
		SET SR_STATUS=2, SR_ESTADO=@EDO, SR_SOLUCION=@SOL, SR_FECHA_FIN = GETDATE(), SR_CONTADOR=@CONT
		WHERE SR_ID=@ID_SERV
		SELECT '1' ID

	END
	ELSE SELECT '0' ID
END 
GO

CREATE PROCEDURE TSP_CREARSERVICIO
(
	@MQ		INT,
	@PROBLEMA NVARCHAR(200)
)
AS BEGIN
	IF EXISTS (SELECT * FROM MAQUINA WHERE MQ_ID=@MQ)
	BEGIN
		DECLARE @NUMSERV AS INT
		DECLARE @EMP AS INT
		SELECT TOP 1 @NUMSERV=SR_NUMSERV+1 FROM SERVICIO ORDER BY SR_NUMSERV desc
		SELECT @EMP=MQ_ID_EMP FROM MAQUINA WHERE MQ_ID=@MQ

		INSERT INTO SERVICIO
		VALUES(0, @NUMSERV, @MQ, @EMP, 1, 1, '', @PROBLEMA, '', '', 0, GETDATE(), GETDATE(), NULL)

		SELECT TOP 1 SR_NUMSERV FROM SERVICIO ORDER BY SR_ID
	END
	ELSE SELECT '0' ID
END
GO



SELECT CN_FOLIO FOLIO, RN_NUMCOPIAS COPIAS, MQ_MODELO MODELO  FROM CONTRATO, RENTA, MAQUINA
WHERE CN_TIPO=2 AND CN_ESTATUS=1 AND CN_ID_CLI=2 AND RN_ID_CONTRATO=CN_ID AND RN_ID_MQ=MQ_ID

SELECT MQ_ID ID  FROM CONTRATO, RENTA, MAQUINA
WHERE CN_TIPO=2 AND CN_ESTATUS=1 AND CN_ID_CLI=2 AND RN_ID_CONTRATO=CN_ID AND RN_ID_MQ=MQ_ID

SELECT * FROM RENTA
SELECT * FROM CLIENTE
SELECT * FROM CONTRATO
SELECT * FROM MAQUINA
SELECT * FROM EMPLEADO
SELECT * FROM SERVICIO

UPDATE CONTRATO
SET CN_FOLIO=2883
WHERE CN_ID=1

--exec sp_who2
--exec kill 56


