UPDATE MAQUINA
SET MQ_FOTO='Xerox.jpg'

CREATE PROCEDURE TSP_AGREGARSOLICITUD
(
	@ID_SERV	INT,
	@PIEZA		NVARCHAR(100),
	@DESC		NVARCHAR(200)
)
AS
BEGIN

	IF EXISTS(SELECT SR_ID ID FROM SERVICIO WHERE SR_ID=@ID_SERV)
	BEGIN
		
		INSERT INTO SOLICITUD VALUES(@ID_SERV, 0, @PIEZA, 1, @DESC) 
		SELECT '1' --AGREGADA
	END
	ELSE SELECT '0' -- NO EXIXSTE EL SERVICIO
END
GO

CREATE PROCEDURE TSP_DATOSMAQUINA
(
	@ID_MQ		INT
)
AS
BEGIN

	IF EXISTS(SELECT MQ_ID FROM MAQUINA WHERE @ID_MQ=MQ_ID)
	BEGIN
		SELECT MQ_ID_EMP EMP, MQ_ID_INV INV, MQ_MODELO MODELO, MQ_NOSERIE NOSERIE, MQ_ESTATUS ESTATUS, MQ_PRECIO PRECIO, MQ_DESCRIPCION DESCR, MQ_CONTADOR CONT, MQ_FOTO FOTO, MQ_ULT_SERVICIO ULT  
		FROM MAQUINA
		WHERE MQ_ID = @ID_MQ
	END

END
GO

ALTER PROCEDURE TSP_TERMINARSERVICIO
(
	@ID_SERV INT,
	@SOL NVARCHAR(500),
	@EDO NVARCHAR(500),
	@CONT INT
)
AS
BEGIN
	IF EXISTS(SELECT * FROM SERVICIO WHERE SR_ID=@ID_SERV)
	BEGIN
		UPDATE SERVICIO
		SET SR_STATUS=2, SR_ESTADO=@EDO, SR_SOLUCION=@SOL, SR_FECHA_FIN = GETDATE(), SR_CONTADOR=@CONT
		WHERE SR_ID=@ID_SERV
		SELECT '1' ID

	END
	ELSE SELECT '0' ID
END 
GO

UPDATE SERVICIO
SET SR_STATUS=1
